<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\..\props\netcore.props" />
    <Import Project="..\..\props\common.props" />
    <Import Project="..\..\props\test.props" />

    <ItemGroup>
        <ProjectReference Include="..\..\src\XiHan.Framework.Data\XiHan.Framework.Data.csproj" />
        <ProjectReference Include="..\..\src\XiHan.Framework.DistributedIds\XiHan.Framework.DistributedIds.csproj" />
        <ProjectReference Include="..\..\src\XiHan.Framework.Quotas\XiHan.Framework.Quotas.csproj" />
        <ProjectReference Include="..\..\src\XiHan.Framework.Quotas.SqlSugar\XiHan.Framework.Quotas.SqlSugar.csproj" />
        <ProjectReference Include="..\..\src\XiHan.Framework.Uow\XiHan.Framework.Uow.csproj" />
    </ItemGroup>

</Project>
