<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\..\props\netcore.props" />
    <Import Project="..\..\props\common.props" />
    <Import Project="..\..\props\test.props" />

    <ItemGroup>
        <ProjectReference Include="..\..\src\XiHan.Framework.Traffic.SqlSugar\XiHan.Framework.Traffic.SqlSugar.csproj" />
    </ItemGroup>

</Project>
