<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\..\props\netcore.props" />
    <Import Project="..\..\props\common.props" />
    <Import Project="..\..\props\version.props" />
    <Import Project="..\..\props\nuget.props" />

    <PropertyGroup>
        <Title>XiHan.Framework.Excel.Abstractions</Title>
        <AssemblyName>XiHan.Framework.Excel.Abstractions</AssemblyName>
        <PackageId>XiHan.Framework.Excel.Abstractions</PackageId>
        <Description>曦寒框架 Excel 导入导出抽象，不含任何 Excel 库依赖</Description>
        <OutputType>Library</OutputType>
    </PropertyGroup>

</Project>
